### ISSUE TITLE
Regularization-parameter lambda for CGLogRegTrainer-constructor is python reserved-word 

### ISSUE THREAD

**Issue by skbidiap** [bioidiap/bob.learn.linear#3]
When I try to use the regularization parameter, using something like:
bob.learn.linear.CGLogRegTrainer(prior=0.5,  lambda=0.001)
I get an error message from Python: SyntaxError: invalid syntax

because the parameter-name 'lambda' matches the python keyword 'lambda'.

**Comment by tiagofrepereira2012** [comment]
Hi,

You are right and we don't have unit tests covering the keyword arguments for this class (only arguments).
So, we can change the name of the keyword argument.
Can we consider such modification as an API modification (so we'll release the 3.x version) @siebenkopf and @anjos ?

For the time being @skbidiap , you can use the regularization as an argument parameter.
The regularization is the 4th one.

```CGLogRegTrainer([prior=0.5, [convergence_threshold=1e-5,
[max_iterations=10000, [lambda=0., [mean_std_norm=False]]]]]) -> new CGLogRegTrainer```

So you can create the object like this

```bob.learn.linear.CGLogRegTrainer(0.5, 1e-5, 10000, 0.001)```

Thanks for the report

**Comment by siebenkopf** [comment]
The API modification is just a minor release, so version 2.1 should be sufficient. Even more, as it is a bug fix (the current keyword doesn't work, so no-one might have used it before), 2.0.6 is also an option.
But, yes, please go ahead and change the parameter name. Be creative in selecting a new one ;-)

**Comment by tiagofrepereira2012** [comment]
Just to let you know @skbidiap I changed the regularization parameter from ```lambda``` to ```reg```
Now the constructor is like this

```CGLogRegTrainer([prior=0.5, [convergence_threshold=1e-5, [max_iterations=10000, [reg=0., [mean_std_norm=False]]]]]) -> new CGLogRegTrainer```
